spring:
  application:
    name: sync-probe
  datasource:
    url: jdbc:postgresql://localhost:5432/syncprobe
    username: jc
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
langchain4j:
  google-ai-gemini:
    chat-model:
      api-key: ${GEMINI_API_KEY}
      model-name: gemini-2.5-flash
    embedding-model:
      api-key: ${GEMINI_API_KEY}
      model-name: gemini-embedding-001
chroma:
  base-url: http://127.0.0.1:8000


